# Generated by Django 5.0.1 on 2024-07-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='static/img/gujarat-1.jpg', upload_to='')),
                ('name', models.CharField(default='NULL', max_length=122)),
                ('city', models.CharField(default='NULL', max_length=122)),
                ('star', models.IntegerField(default=5, max_length=5)),
                ('days', models.IntegerField(default=2, max_length=100)),
                ('person', models.IntegerField(default=4, max_length=99)),
                ('price', models.IntegerField(default=10000, max_length=999999)),
            ],
        ),
    ]
